### ISSUE TITLE
Add "package" command, to measure dedicated package size

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/lines#29]
To quickly check which package takes more space.

API:

```bash
bin/lines package nunomaduro/collision
```

In the background:

````
mkdir isolated
cd isolated
composer require nunomaduro/collision
bin/lines measure isolated
rm -rf isolated
````

Show results... enjoy :sunglasses:

**Comment by MarcinGladkowski** [comment]
Hi! 

Are you open to make a PR to this project ? I will be happy to work on this feature.

Have a nice day

**Comment by TomasVotruba** [comment]
Hi, thanks for reaching out.

I actually forgot about this issue and found a simple solution to achieve this one.
It was one time job and I don't think it's worth repetetive use case.

What is your use case for this one?

**Comment by MarcinGladkowski** [comment]
I haven't special case here. I resolving sometimes issues in open source. Thanks for fast response.

**Comment by TomasVotruba** [comment]
I see, thanks for help :+1:
