### ISSUE TITLE
[Bug] Console output style and `--no-ansi` has no effect

### ISSUE THREAD

**Issue by sebb-m0** [TomasVotruba/lines#35]
When I use lines in my console (iTerm, agnoster theme) the font for relative is not visible:

![Screenshot 2023-09-08 at 09 40 06](https://github.com/TomasVotruba/lines/assets/126587502/191b65ff-fd66-49cb-af59-e0860ff6d835)

the Content is there, so if I mark the output, I can see it:

![Screenshot 2023-09-08 at 09 41 24](https://github.com/TomasVotruba/lines/assets/126587502/ee78bde4-7245-4186-ab43-a324e1b9b489)

So I thought, the option `--no-ansi` would solve the problem, but this option is ignored and the output is the same as without the option:

![Screenshot 2023-09-08 at 09 43 00](https://github.com/TomasVotruba/lines/assets/126587502/fad0cbc2-bfa1-4c66-847c-430c06e46f33)

**Comment by TomasVotruba** [comment]
I think there is nothing we can do, as we're using symofny/console package here. 
It should be reported there.

**Comment by sebb-m0** [comment]
> Do you think it's related to termwind?

I think so. Symfony console command should do it as expected. Looks like the termwind is ignoring it and put the styles afterwards.

**Comment by TomasVotruba** [comment]
@sebb-m0  In that case I think it should be opened in termwind repository, as we only use 3rd party package here as well.

**Comment by xiCO2k** [comment]
@sebb-m0 yes if you can report that on Termwind, I can check it later.

**Comment by sebb-m0** [comment]
-> https://github.com/nunomaduro/termwind/issues/175
