### ISSUE TITLE
Add Number of Tests to Measure Results

### ISSUE THREAD

**Issue by JosephLeedy** [TomasVotruba/lines#36]
Thanks for the great tool! I've been looking for something like this since PHPLOC was abandoned.

It would great to have a line item in the output of `lines measure` to show how many tests were found so that the quality of a codebase can be quickly assessed.

**Comment by TomasVotruba** [comment]
That sounds good :+1:  Just my time for open-source is limited.

Would you like to contribute this?

**Comment by JosephLeedy** [comment]
Apologies for the delay in responding. I'd love to implement this, if I only had the time. Maybe someone else will come along and pick it up in the meantime.
